name: test and deploy

on:
  push:
    branches: [ci_experiment]
  pull_request:
    branches: [ci_experiment]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # Install poetry. There are some redundant looking steps here. Windows
      # and Linux will work without the first two, but Mac (only Mac) will fail
      # unless you do this checkout, setup, checkout, install, setup sequence.
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - run: poetry config virtualenvs.in-project false && poetry install

      - name: Run tests
        run: poetry run pytest -v

  # Pyright fails EVERY TIME when called through pre-commit.ci with "Temporary
  # failure in name resolution". Bypass the pre-commit Pyright, and use a
  # Pyright pre-commit action instead.
  pyright:
    runs-on: ubuntu-latest
    name: "Run Pyright"
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - uses: jakebailey/pyright-action@v1
        with:
          project: "pyproject.toml"

  # If the tests pass, try to bump the version number. If no bump is warranted,
  # pass silently.
  bump_version:
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    continue-on-error: true
    needs: [tests, pyright]
    if: github.ref == 'refs/heads/ci_experiment'
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.COMMITIZEN_BUMP }}"
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.COMMITIZEN_BUMP }}
      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"

  # Deploy on test.pypi when pushed to dev if all tests pass and if commit is
  # tagged (a tagged release implies the version was bumped.)
  deploy-on-aaaaa:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: [tests]
    if: github.ref == 'refs/heads/dev' && startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v3
      - name: Run image
        uses: abatilo/actions-poetry@v2
      - name: deploy on test.pypi
        run: |
          poetry config repositories.test-pypi https://test.pypi.org/legacy/
          poetry publish -r test-pypi --build --username __token__ --password ${{ secrets.TEST_PYPI_API_TOKEN }}

  # Deploy on test.pypi when pushed to dev if all tests pass and if commit is
  # tagged (a tagged release implies the version was bumped.)
  deploy-on-testpypi:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: [tests]
    if: github.ref_name == 'ci_experiment' || !startsWith(github.ref, 'refs/tags')
    steps:
      - run: echo "ref_name is ${{ github.ref_name }} ref is ${{ github.ref }}"

  # Deploy on .pypi when pushed to main if all tests pass and if commit is
  # tagged (a tagged release implies the version was bumped.)
  deploy-on-pypi:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: [tests]
    if: github.ref == 'refs/heads/master' && startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v3
      - name: Run image
        uses: abatilo/actions-poetry@v2
      - name: deploy on pypi
        run: |
          poetry publish --build --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
